export const allProjectsInfo = [
    {
        id: '0',
        title: 'Rinha backend 2025 - payment processor',
        des: 'Participação da rinha backend 2025.',
        category: 'nodejs - redis - bullmq - nginx',
        repo: 'https://github.com/ThiLourenco/rinha-de-backend-2025',
        link: 'https://github.com/zanfranceschi/rinha-de-backend-2025',
    },
    {
        id: '1',
        title: 'ChatBot Miles Davis',
        des: 'Chat para integração com AI',
        category: 'nextjs - typescript',
        repo: 'https://github.com/ThiLourenco/miles_davis',
        link: 'https://github.com/ThiLourenco/miles_davis',
    },
    {
        id: '2',
        title: 'Delivery Server',
        des: 'Backend em Node.js de uma aplicação de delivery',
        category: 'nodejs - typescript - express - prisma - jest',
        repo: 'https://github.com/ThiLourenco/delivery-backend',
        link: 'https://github.com/ThiLourenco/delivery-backend',
    },
    {
        id: '3',
        title: 'Polls-backend',
        des: 'Backend do sistema de enquetes',
        category: 'nodejs - typescript - fastify - prisma - zod - ioredis',
        repo: 'https://github.com/ThiLourenco/polls-backend',
        link: 'https://github.com/ThiLourenco/polls-backend',
    },
    {
        id: '4',
        title: 'Store 88',
        des: 'E-commerce moderno com integração com a plataforma de processamento de pagamento Stripe.',
        category: 'nextjs - typescript - tailwindcss - stripe',
        repo: 'https://github.com/ThiLourenco/e-commerce',
        link: 'https://e-commerce-thilourenco.vercel.app/',
    },
    {
        id: '5',
        title: 'Rentalx',
        des: 'Backend em Node.js usando princípios SOLID.',
        category: 'nodejs - typescript',
        repo: 'https://github.com/ThiLourenco/rentalx',
        link: 'https://github.com/ThiLourenco/rentalx',
    },
    {
        id: '6',
        title: 'Serviço de notificação',
        des: 'Microsserviço - Serviço de notificação desenvolvido em NestJS e Prisma ORM.',
        category: 'nodejs - nestJS - typescript - react',
        repo: 'https://github.com/ThiLourenco/notification-service',
        link: 'https://github.com/ThiLourenco/notification-service',
    },
    {
        id: '7',
        title: 'Pitu',
        des: 'Pitu é um micro-SaaS simples, mas eficiente para encurtar links e URLs.',
        category: 'nodejs - typescript - react',
        repo: 'https://github.com/ThiLourenco/pitu',
        link: 'https://github.com/ThiLourenco/pitu',
    },
    {
        id: '8',
        title: 'Habits',
        des: 'Aplicação fullstack para registro de hábitos diários.',
        category: 'react - react-native - nodejs - express',
        repo: 'https://github.com/ThiLourenco/habit',
        link: 'https://github.com/ThiLourenco/habit',
    },
    {
        id: '9',
        title: 'Rocket Help',
        des: 'A aplicação para gerenciar em tempo real solicitações de manutenção e suporte a equipamentos, desenvolvido com Expo, Typescript e Firebase.',
        category: 'nodejs - react - react-native - typescript',
        repo: 'https://github.com/ThiLourenco/rockethelp',
        link: 'https://github.com/ThiLourenco/rockethelp',
    },
    {
        id: '10',
        title: 'Chat JS',
        des: 'Chat multiplataforma usando CLI (interface de linha de comando).',
        category: 'javascript - nodejs - cli',
        repo: 'https://github.com/ThiLourenco/chat-js',
        link: 'https://www.npmjs.com/package/@thidotl17/hacker-chat-client',
    },
    {
        id: '11',
        title: 'Coffee Delivery',
        des: 'E-commerce para realizar pedidos de café.',
        category: 'typescript - react  - React-hook-form - Zod',
        repo: 'https://github.com/ThiLourenco/coffee-delivery',
        link: 'https://coffee-delivery-thilourenco.vercel.app/',
    },
    {
        id: '12',
        title: '30 Day Vanilla JS',
        des: 'Desafio JS Vanilla de 30 dias.',
        category: 'javascript',
        repo: 'https://github.com/ThiLourenco/JS30days',
        link: 'https://thilourenco.github.io/JS30days/',
    },
    {
        id: '13',
        title: 'Dev Finance',
        des: 'Aplicação de controle financeiro com persistência de dados no Local Storage.',
        category: 'javascript',
        repo: 'https://github.com/ThiLourenco/app-finance',
        link: 'https://thilourenco.github.io/app-finance/',
    },
    {
        id: '14',
        title: 'DoctorCare',
        des: 'DoctorCare é uma página institucional no formato One Page, responsiva, para usar em diversos tipos de micros, pequenas e médias empresas.',
        category: 'javascript',
        repo: 'https://github.com/ThiLourenco/doctor-care',
        link: 'https://thilourenco.github.io/doctor-care/',
    },
    {
        id: '15',
        title: 'Blog',
        des: 'Blog desenvolvido em React.js consumindo a API do Github onde retorna as postagem através de "issues" do Github. ',
        category: 'react - styled-components - typescript',
        repo: 'https://github.com/ThiLourenco/blog',
        link: 'https://blog-thilourenco.vercel.app/',
    },
    {
        id: '16',
        title: 'Ignite Lab React',
        des: 'Uma plataforma para assistir videoaulas online.',
        category: 'react - typescript - graphql - headless CMS',
        repo: 'https://github.com/ThiLourenco/ignite-lab-react',
        link: 'https://ignite-lab-react-thilourenco.vercel.app/',
    },
]

export const favProjects = [
    {
        id: 1,
        image:
            'https://portfolio-next-thilourenco.vercel.app/static/images/store.png',
        title: '',
        repo: 'https://github.com/ThiLourenco/e-commerce',
        link: 'https://e-commerce-thilourenco.vercel.app/',
    },
    {
        id: 2,
        image:
            'https://thilourenco.dev.br/_next/image?url=https%3A%2F%2Fmedia.graphassets.com%2Fx2ctlyrgTRC91wCSK0dj&w=640&q=100',
        title: '',
        repo: 'https://github.com/ThiLourenco/rinha-de-backend-2025',
        link: '',
    },
    {
        id: 3,
        image: 'https://thilourenco.dev.br/static/images/miles-ai.png',
        title: '',
        repo: 'https://github.com/ThiLourenco/chat-ia',
        link: 'https://chat-ia-dun.vercel.app/',
    },
    {
        id: 4,
        image:
            'https://thilourenco.dev.br/_next/image?url=https%3A%2F%2Fmedia.graphassets.com%2FgCv97gwMRJaTLuqmjn3y&w=640&q=100',
        title: '',
        repo: 'https://github.com/ThiLourenco/rentalx',
        link: '',
    },
]